name: Auto Commit

on:
  schedule:
    - cron: "0 * * * *"  # a cada hora
  workflow_dispatch: # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checar repositório
        uses: actions/checkout@v3

      - name: Fazer alteração de teste
        run: |
          date >> log.txt

      - name: Commit e push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Commit automático: $(date +'%Y-%m-%d %H:%M:%S')"
